/tmp/python-build.20240827235536.29272/Python-3.12.0/Python/errors.c: 40 - 54
--------------------------------------------------------------------------------

/tmp/python-build.20240827235536.29272/Python-3.12.0/Python/errors.c: 61 - 62
--------------------------------------------------------------------------------

/tmp/python-build.20240827235536.29272/Python-3.12.0/./Include/internal/pycore_pystate.h: 82 - 82
--------------------------------------------------------------------------------

/tmp/python-build.20240827235536.29272/Python-3.12.0/./Include/object.h: 220 - 220
--------------------------------------------------------------------------------

/tmp/python-build.20240827235536.29272/Python-3.12.0/./Include/object.h: 243 - 243
--------------------------------------------------------------------------------

/tmp/python-build.20240827235536.29272/Python-3.12.0/./Include/object.h: 701 - 706
--------------------------------------------------------------------------------

/tmp/python-build.20240827235536.29272/Python-3.12.0/./Include/object.h: 967 - 967
--------------------------------------------------------------------------------

/tmp/python-build.20240827235536.29272/Python-3.12.0/./Include/internal/pycore_call.h: 44 - 44
--------------------------------------------------------------------------------

/tmp/python-build.20240827235536.29272/Python-3.12.0/./Include/internal/pycore_call.h: 53 - 53
--------------------------------------------------------------------------------

/tmp/python-build.20240827235536.29272/Python-3.12.0/./Include/internal/pycore_call.h: 88 - 93
--------------------------------------------------------------------------------

