/tmp/python-build.20240827235536.29272/Python-3.12.0/./Include/internal/pycore_pystate.h: 82 - 82
--------------------------------------------------------------------------------

/tmp/python-build.20240827235536.29272/Python-3.12.0/./Include/internal/pycore_pyerrors.h: 23 - 23
--------------------------------------------------------------------------------

/tmp/python-build.20240827235536.29272/Python-3.12.0/./Include/object.h: 243 - 243
--------------------------------------------------------------------------------

/tmp/python-build.20240827235536.29272/Python-3.12.0/./Include/object.h: 701 - 706
--------------------------------------------------------------------------------

/tmp/python-build.20240827235536.29272/Python-3.12.0/Objects/call.c: 14 - 15
--------------------------------------------------------------------------------

/tmp/python-build.20240827235536.29272/Python-3.12.0/Objects/call.c: 896 - 916
--------------------------------------------------------------------------------

