/usr/local/src/conda/python-3.12.0/Include/internal/pycore_pystate.h: 82 - 82
--------------------------------------------------------------------------------

/usr/local/src/conda/python-3.12.0/Objects/call.c: 28 - 29
--------------------------------------------------------------------------------

/usr/local/src/conda/python-3.12.0/Include/internal/pycore_pyerrors.h: 23 - 23
--------------------------------------------------------------------------------

/usr/local/src/conda/python-3.12.0/Objects/methodobject.c: 518 - 518
--------------------------------------------------------------------------------

/usr/local/src/conda/python-3.12.0/Objects/methodobject.c: 525 - 525
--------------------------------------------------------------------------------

/usr/local/src/conda/python-3.12.0/Objects/methodobject.c: 536 - 542
--------------------------------------------------------------------------------

/usr/local/src/conda/python-3.12.0/Objects/methodobject.c: 548 - 551
--------------------------------------------------------------------------------

/usr/local/src/conda/python-3.12.0/Include/cpython/methodobject.h: 41 - 41
--------------------------------------------------------------------------------

/usr/local/src/conda/python-3.12.0/Include/cpython/methodobject.h: 47 - 55
--------------------------------------------------------------------------------

