address;source_location;insn;indent
0x5c1470;/usr/local/src/conda/python-3.12.0/Objects/exceptions.c:579;PUSH	%R12;
0x5c1472;:0;PUSH	%RBP;
0x5c1473;:0;MOV	%RSI,%RBP;
0x5c1476;:0;PUSH	%RBX;
0x5c1477;/usr/local/src/conda/python-3.12.0/Objects/exceptions.c:579;MOV	%RDI,%RBX;
0x5c147a;/usr/local/src/conda/python-3.12.0/Include/object.h:234;MOV	0x10(%RSI),%R12;
0x5c147e;/usr/local/src/conda/python-3.12.0/Objects/exceptions.c:73;TEST	%RDX,%RDX;
0x5c1481;:0;JNE	483426 <StopIteration_init.cold>;
0x5c1487;/usr/local/src/conda/python-3.12.0/Include/object.h:644;MOV	(%RSI),%EDX;
0x5c1489;/usr/local/src/conda/python-3.12.0/Objects/exceptions.c:76;MOV	0x18(%RDI),%RDI;
0x5c148d;/usr/local/src/conda/python-3.12.0/Include/object.h:644;INC	%EDX;
0x5c148f;/usr/local/src/conda/python-3.12.0/Include/object.h:644;JE	5c14d2 <StopIteration_init+0x62>;
0x5c1491;/usr/local/src/conda/python-3.12.0/Include/object.h:647;MOV	%EDX,(%RBP);
0x5c1494;/usr/local/src/conda/python-3.12.0/Objects/exceptions.c:76;MOV	%RBP,0x18(%RBX);
0x5c1498;/usr/local/src/conda/python-3.12.0/Include/object.h:798;TEST	%RDI,%RDI;
0x5c149b;:0;JE	5c14ac <StopIteration_init+0x3c>;
0x5c149d;/usr/local/src/conda/python-3.12.0/Include/object.h:243;MOV	(%RDI),%RCX;
0x5c14a0;/usr/local/src/conda/python-3.12.0/Include/object.h:701;TEST	%ECX,%ECX;
0x5c14a2;:0;JS	5c14ac <StopIteration_init+0x3c>;
0x5c14a4;/usr/local/src/conda/python-3.12.0/Include/object.h:705;DEC	%RCX;
0x5c14a7;/usr/local/src/conda/python-3.12.0/Include/object.h:705;MOV	%RCX,(%RDI);
0x5c14aa;:0;JE	5c14dd <StopIteration_init+0x6d>;
0x5c14ac;/usr/local/src/conda/python-3.12.0/Objects/exceptions.c:585;MOV	0x48(%RBX),%RDI;
0x5c14b0;/usr/local/src/conda/python-3.12.0/Objects/exceptions.c:585;TEST	%RDI,%RDI;
0x5c14b3;:0;JNE	5c1501 <StopIteration_init+0x91>;
0x5c14b5;/usr/local/src/conda/python-3.12.0/Objects/exceptions.c:586;TEST	%R12,%R12;
0x5c14b8;:0;JG	5c14f0 <StopIteration_init+0x80>;
0x5c14ba;/usr/local/src/conda/python-3.12.0/Objects/exceptions.c:589;MOV	$0x942580,%EDI;
0x5c14bf;/usr/local/src/conda/python-3.12.0/Include/object.h:644;MOV	(%RDI),%R8D;
0x5c14c2;:0;INC	%R8D;
0x5c14c5;/usr/local/src/conda/python-3.12.0/Include/object.h:644;JNE	5c14f6 <StopIteration_init+0x86>;
0x5c14c7;/usr/local/src/conda/python-3.12.0/Objects/exceptions.c:590;MOV	%RDI,0x48(%RBX);
0x5c14cb;/usr/local/src/conda/python-3.12.0/Objects/exceptions.c:591;XOR	%EAX,%EAX;
0x5c14cd;/usr/local/src/conda/python-3.12.0/Objects/exceptions.c:592;POP	%RBX;
0x5c14ce;/usr/local/src/conda/python-3.12.0/Objects/exceptions.c:592;POP	%RBP;
0x5c14cf;/usr/local/src/conda/python-3.12.0/Objects/exceptions.c:592;POP	%R12;
0x5c14d1;/usr/local/src/conda/python-3.12.0/Objects/exceptions.c:592;RET;
0x5c14d2;/usr/local/src/conda/python-3.12.0/Objects/exceptions.c:76;MOV	%RBP,0x18(%RBX);
0x5c14d6;/usr/local/src/conda/python-3.12.0/Include/object.h:798;TEST	%RDI,%RDI;
0x5c14d9;:0;JNE	5c149d <StopIteration_init+0x2d>;
0x5c14db;/usr/local/src/conda/python-3.12.0/Include/object.h:798;JMP	5c14ac <StopIteration_init+0x3c>;
0x5c14dd;/usr/local/src/conda/python-3.12.0/Include/object.h:706;CALL	50c940 <_Py_Dealloc>;
0x5c14e2;/usr/local/src/conda/python-3.12.0/Objects/exceptions.c:585;MOV	0x48(%RBX),%RDI;
0x5c14e6;/usr/local/src/conda/python-3.12.0/Objects/exceptions.c:585;TEST	%RDI,%RDI;
0x5c14e9;:0;JE	5c14b5 <StopIteration_init+0x45>;
0x5c14eb;:0;JMP	48344e <StopIteration_init.cold+0x28>;
0x5c14f0;/usr/local/src/conda/python-3.12.0/Objects/exceptions.c:587;MOV	0x18(%RBP),%RDI;
0x5c14f4;/usr/local/src/conda/python-3.12.0/Objects/exceptions.c:587;JMP	5c14bf <StopIteration_init+0x4f>;
0x5c14f6;/usr/local/src/conda/python-3.12.0/Include/object.h:647;MOV	%R8D,(%RDI);
0x5c14f9;/usr/local/src/conda/python-3.12.0/Objects/exceptions.c:591;XOR	%EAX,%EAX;
0x5c14fb;/usr/local/src/conda/python-3.12.0/Objects/exceptions.c:590;MOV	%RDI,0x48(%RBX);
0x5c14ff;/usr/local/src/conda/python-3.12.0/Objects/exceptions.c:591;JMP	5c14cd <StopIteration_init+0x5d>;
0x5c1501;/usr/local/src/conda/python-3.12.0/Objects/exceptions.c:591;JMP	48344e <StopIteration_init.cold+0x28>;
0x5c1506;/usr/local/src/conda/python-3.12.0/Objects/exceptions.c:591;NOPW	%CS:(%RAX,%RAX,1);
