/usr/local/src/conda/python-3.9.19/Include/internal/pycore_pystate.h: 55 - 55
--------------------------------------------------------------------------------

/usr/local/src/conda/python-3.9.19/Python/errors.c: 261 - 270
--------------------------------------------------------------------------------

/usr/local/src/conda/python-3.9.19/Python/errors.c: 279 - 282
--------------------------------------------------------------------------------

/usr/local/src/conda/python-3.9.19/Python/errors.c: 299 - 302
--------------------------------------------------------------------------------

/usr/local/src/conda/python-3.9.19/Include/internal/pycore_pyerrors.h: 14 - 14
--------------------------------------------------------------------------------

/usr/local/src/conda/python-3.9.19/Include/object.h: 628 - 630
--------------------------------------------------------------------------------

/usr/local/src/conda/python-3.9.19/Objects/typeobject.c: 1412 - 1417
--------------------------------------------------------------------------------

/usr/local/src/conda/python-3.9.19/Objects/typeobject.c: 1425 - 1433
--------------------------------------------------------------------------------

