/usr/local/src/conda/python-3.12.0/Include/internal/pycore_pystate.h: 82 - 82
--------------------------------------------------------------------------------

/usr/local/src/conda/python-3.12.0/Include/internal/pycore_call.h: 44 - 44
--------------------------------------------------------------------------------

/usr/local/src/conda/python-3.12.0/Include/internal/pycore_call.h: 88 - 92
--------------------------------------------------------------------------------

/usr/local/src/conda/python-3.12.0/Objects/call.c: 28 - 29
--------------------------------------------------------------------------------

/usr/local/src/conda/python-3.12.0/Objects/call.c: 323 - 327
--------------------------------------------------------------------------------

/usr/local/src/conda/python-3.12.0/Include/internal/pycore_pyerrors.h: 23 - 23
--------------------------------------------------------------------------------

/usr/local/src/conda/python-3.12.0/Include/object.h: 220 - 220
--------------------------------------------------------------------------------

/usr/local/src/conda/python-3.12.0/Include/cpython/abstract.h: 60 - 60
--------------------------------------------------------------------------------

